---
version: "2"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=100
      - TZ=${TZ}
    volumes:
      - /sharedfolders/appdata/nextcloud:/config
      - /sharedfolders/nextcloud:/data
    ports:
      - 444:443
    restart: unless-stopped
    network_mode: bridge
  nextclouddb:
    image: postgres
    container_name: nextclouddb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=nextcloud
    volumes:
      - /sharedfolders/appdata/nextclouddb:/var/lib/postgresql/data
    ports:
      - "5432:5432/tcp"
    restart: unless-stopped
    network_mode: bridge
